# Generated by Django 5.1.2 on 2024-10-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nomre_Usuario',
            new_name='nombre_Usuario',
        ),
    ]
