# Generated by Django 5.1.2 on 2024-10-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_nomre_usuario_usuarios_nombre_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
    ]
